### ISSUE TITLE
Visualize signal flow

### ISSUE THREAD

**Issue by dimitriblock** [myriadrf/ScratchRadio#2]
Up to now the commands are visualized. Is there a way to more visualize the signal flow instead?

An easy change would be to add the `connect` functions to `create*Sink` functions. So, instead if two functions `createDisplaySink` and `connectComponents` there is only `createDisplaySinkAndConnect`

**Comment by zynaptic** [comment]
You're right that there has to be a more intuitive way to present this to new users. The current approach is lifted directly from the way which it is done in LuaRadio and exposes a bit too much of the working (as well as being potentially awkward when it comes to introducing error checking). I was going to see if any of the 'structure' blocks could help in some way, but unfortunately they're not well documented for use in extensions. This is all still quite experimental so I'm definitely open to suggestions.

**Comment by zynaptic** [comment]
The radio setup can now be visualized as a signal flow, within the constraints of what Scratch blocks will allow - the new programming guide describes how this looks: https://wiki.myriadrf.org/ScratchRadio:Programming

Thanks for raising the issue - hopefully doing things this way will now make it easier to pick up.
